name: ASP.NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build

    - name: Run tests
      run: dotnet test

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish the application
      run: dotnet publish 03-app-dotnet/app-dotnet.csproj -c Release -o website

